version: '3.8'

services:
  sales-dashboard:
    build:
      context: .
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    stdin_open: true
    tty: true
    networks:
      - dashboard-network

networks:
  dashboard-network:
    driver: bridge